// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZxCxek1s0e4QxGCw8zJQZrPtfzj16CUk',
    appId: '1:153837690543:web:333604d292f8857bb2fe5a',
    messagingSenderId: '153837690543',
    projectId: 'demoapp-8dd86',
    authDomain: 'demoapp-8dd86.firebaseapp.com',
    storageBucket: 'demoapp-8dd86.firebasestorage.app',
    measurementId: 'G-0QEVDBTCJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMzMlgQPSOjIsRNR2krKpoEicIe6c1p2o',
    appId: '1:153837690543:android:e8c4e36ffa8ba77fb2fe5a',
    messagingSenderId: '153837690543',
    projectId: 'demoapp-8dd86',
    storageBucket: 'demoapp-8dd86.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnicLI5sKXXt83xVVJ8jChPfi1oke7eWg',
    appId: '1:153837690543:ios:fa55e0e7f81e2c0ab2fe5a',
    messagingSenderId: '153837690543',
    projectId: 'demoapp-8dd86',
    storageBucket: 'demoapp-8dd86.firebasestorage.app',
    iosBundleId: 'com.example.demoapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnicLI5sKXXt83xVVJ8jChPfi1oke7eWg',
    appId: '1:153837690543:ios:fa55e0e7f81e2c0ab2fe5a',
    messagingSenderId: '153837690543',
    projectId: 'demoapp-8dd86',
    storageBucket: 'demoapp-8dd86.firebasestorage.app',
    iosBundleId: 'com.example.demoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZxCxek1s0e4QxGCw8zJQZrPtfzj16CUk',
    appId: '1:153837690543:web:2861d7160f2f1ed1b2fe5a',
    messagingSenderId: '153837690543',
    projectId: 'demoapp-8dd86',
    authDomain: 'demoapp-8dd86.firebaseapp.com',
    storageBucket: 'demoapp-8dd86.firebasestorage.app',
    measurementId: 'G-F0C2Y1TQZC',
  );
}
